// <auto-generated />
using korteriyhistu.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace korteriyhistu.Migrations.LogEntries
{
    [DbContext(typeof(LogEntriesContext))]
    [Migration("20190630122439_RemovedBillReferenceNavPropertyw")]
    partial class RemovedBillReferenceNavPropertyw
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("korteriyhistu.Models.LogEntry", b =>
                {
                    b.Property<string>("LogEntryId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BillId");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Message");

                    b.HasKey("LogEntryId");

                    b.ToTable("LogEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
